// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwAg1ejECVHLuY7qt6wy5pKMSL5Mxuyc',
    appId: '1:812521849481:web:865c1a20051eedd0157c58',
    messagingSenderId: '812521849481',
    projectId: 'chill-app-809e7',
    authDomain: 'chill-app-809e7.firebaseapp.com',
    storageBucket: 'chill-app-809e7.appspot.com',
    measurementId: 'G-VB74CDMW2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhIOfW2U9Cu8UY8_3rSYHtLv3bmZ8WjjE',
    appId: '1:812521849481:android:a1484a46acf78341157c58',
    messagingSenderId: '812521849481',
    projectId: 'chill-app-809e7',
    storageBucket: 'chill-app-809e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjKTu_Mcd1T4gt3FmSn15RNqKhmH1p5A',
    appId: '1:812521849481:ios:5a3da67b81a025e3157c58',
    messagingSenderId: '812521849481',
    projectId: 'chill-app-809e7',
    storageBucket: 'chill-app-809e7.appspot.com',
    iosBundleId: 'com.example.chillAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjKTu_Mcd1T4gt3FmSn15RNqKhmH1p5A',
    appId: '1:812521849481:ios:5a3da67b81a025e3157c58',
    messagingSenderId: '812521849481',
    projectId: 'chill-app-809e7',
    storageBucket: 'chill-app-809e7.appspot.com',
    iosBundleId: 'com.example.chillAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlwAg1ejECVHLuY7qt6wy5pKMSL5Mxuyc',
    appId: '1:812521849481:web:a4d47dd7a80cc39a157c58',
    messagingSenderId: '812521849481',
    projectId: 'chill-app-809e7',
    authDomain: 'chill-app-809e7.firebaseapp.com',
    storageBucket: 'chill-app-809e7.appspot.com',
    measurementId: 'G-676XQSZVMY',
  );
}
